### PR TITLE
Issue #39 Change extension of application.css to scss

### LINKED ISSUE #39: Change extension of application.css to scss

### PR DESCRIPTION
**Pull request by Kacper3331**
Closes #39

### CODE REVIEW

**Comment by student-tomasz** [comment]
What is the point of this PR? Do you have any views that need that file?

I sound like an asshole, but pull requests aren't for atomic changes. When you'll add views, that actually need a custom stylesheet, and you fill it with rules, then this file will be changed. But right now this PR isn't really doing anything.

**Comment by Kacper3331** [comment]
@student-tomasz I asked Oskar if I should make a Issue to change this file and he said that "yes" so I made it also I need this file if I want to configure bootstrap.

**Comment by student-tomasz** [comment]
Sure, because you can't push to `master` but that's besides the point. When you'll have working views, and you change this file along the way, then you will have a proper PR. But then the PR's purpose won't be to just change a single file's name, but to add an actual new functionality. Right now this change is negligible and brings nothing the project in the current state.

**Comment by Kacper3331** [comment]
Right now, it doesn't but in the gemfile you used gem 'sass-rails' which states that in our project we're going to use sass instead of normal css. So right now I fix the problem with this file.

**Comment by student-tomasz** [comment]
You can still use regular CSS files even with SASS gem plugged-in. There is no problem.

**Comment by Kacper3331** [comment]
Okay but I think if we use sass then our main application file should have a scss extension if only simple css then css extension. I think that's more logical instead of using sass in css file.

**Comment by agalkiewicz** [comment]
It is not really important right now. :)

**Comment by Kacper3331** [comment]
So what do you want me to do? Close this PR and just make this change as part of my original Issue?

**Comment by student-tomasz** [comment]
Don't get me wrong. I'm all for using SCSS, I can't phantom using plain CSS.

But this minor change will be a part of a larger PR in which you change views, and add actual stylesheets. So close this one, move on to an issue with actual changes.

**Comment by Kacper3331** [comment]
I want to use bootstrap-sass in our project so I will change this file anyway.

**Pull request closed without merging**
