### PR TITLE
Fix input fields in sign in page to be responsive

### LINKED ISSUE #110: Fix input fields in sign in page to be responsive

### PR DESCRIPTION
**Pull request by Kacper3331**
Closes #110

### CODE REVIEW

**Comment by agalkiewicz** [comment]
:+1:

**Comment by nodzy** [comment]
:+1:

**Comment by shadre** [comment]
Sorry, I don't think this is how the page should respond to this width at all:
resp
One "box" should be below another, not like this. ^

**Comment by shadre** [comment]
The `<div>`s are stacking well now.

There are two more slight changes required in my opinion, however. Both are visible in smaller resolutions (you can use browser's developer tools to see a webpage as seen on different devices):
1. Fix the space between green [Let me in!] button and "Sign up" header (should be bigger), and fix the space between the "Sign up" header and the text below it (should be smaller). Please see the problem below: 
   sign up
   It's confusing, because a user can think he/she should click the green button to Sign up, which is not the case.
2. Add some space below the blue [Sign me up!] - button - currently there is no space between it and bottom edge of the screen on smaller devices. See below:
   blue button

**Comment by shadre** [comment]
:+1:

**Pull request merged**
